kind: Deployment
apiVersion: apps/v1
metadata:
  name: gcp-pd-csi-driver-controller
  namespace: openshift-gcp-pd-csi-driver
spec:
  serviceName: "gcp-pd-csi-driver-controller"
  replicas: 1
  selector:
    matchLabels:
      app: gcp-pd-csi-driver-controller
  template:
    metadata:
      labels:
        app: gcp-pd-csi-driver-controller
    spec:
      hostNetwork: true
      serviceAccountName: gcp-pd-csi-driver-controller-sa
      priorityclassname: system-cluster-critical
      tolerations:
        - key: CriticalAddonsonly
          operator: Exists
      containers:
        - name: csi-driver
          image: quay.io/bertinatto/pd-driver
          args:
            - "--v=5"
            - "--endpoint=unix:/csi/csi.sock"
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/cloud-sa/service_account.json"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: cloud-sa-volume
              readOnly: true
              mountPath: "/etc/cloud-sa"
        - name: csi-provisioner
          image: quay.io/openshift/origin-csi-external-provisioner:latest
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--feature-gates=Topology=true"
          # - "--run-controller-service=false" # disable the controller service of the CSI driver
          # - "--run-node-service=false"       # disable the node service of the CSI driver
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          image: quay.io/openshift/origin-csi-external-attacher:latest
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-resizer
          image: quay.io/openshift/origin-csi-external-resizer:latest
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: cloud-sa-volume
          secret:
            secretName: gcp-cloud-credentials
  # This is needed due to https://github.com/kubernetes-sigs/kustomize/issues/504
  volumeClaimTemplates: []
